### ISSUE TITLE
Background Image jumping on reload

### ISSUE THREAD

**Issue by sbstn2** [nk-o/jarallax#136]
The Background image is jumping everytime i reload the page. Even on the demo site from here.
How to fix this?

**Comment by nk-o** [comment]
You can try to use [MutationObserver](https://developer.mozilla.org/en/docs/Web/API/MutationObserver). Immediately initialize parallax after the needed block rendered.

The problem only in the loading scripts, you will need to add scripts in the <head> section (I don't recommend it because your content will be loaded slower).

Also, you can try to use lazy loading for background images.
