### ISSUE TITLE
Jarallax element with background image

### ISSUE THREAD

**Issue by simopetrelli** [nk-o/jarallax#137]
Hi Nikita,
Thank you so much for creating this plugin and thank you for taking the time to keep it alive.

I can not display an image in the background-image with data-jarallax-element.
here the test: https://codepen.io/sparrowandsnow/pen/XOYmZp

is a plugin limit? or I missed something.

Thanks a lot

**Comment by nk-o** [comment]
Hi.

Yes, as the Jarallax originally is background parallax library, Elements extension also tried to work with backgrounds. It can be fixed by disabling these lines when Elements extension is used.

https://github.com/nk-o/jarallax/blob/406de2c2af747e985f9aa910deaac7c9841c80da/src/jarallax.esm.js#L444-L449

**Comment by simopetrelli** [comment]
Thanks for the reply.
The image can be seen but the animation, unfortunately, does not work.

All the best
