### ISSUE TITLE
Making another background image fully dissapear

### ISSUE THREAD

**Issue by shafickr** [nk-o/jarallax#164]
### Issue description:
<img width="1440" alt="Screenshot 2020-01-31 at 12 49 55" src="https://user-images.githubusercontent.com/32784609/73515715-dddf4900-4428-11ea-9829-993aeb1dcc3f.png">

I'm using jarallax with nuxt.js framework. when I scrolled to bottom it worked fine, but when I scrolled back to top, there was another background image appear. How can I fix it? 

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html

```

```javascript

```

**Comment by nk-o** [comment]
Hi.

May I see any online example? [Codepen](https://codepen.io/) will be perfect to check the bug.

**Comment by shafickr** [comment]
This is the preview url:
https://nifty-sinoussi-055df5.netlify.com/

**Comment by nk-o** [comment]
I see you used custom styles for images. Jarallax is calculating only when image container is in the viewport, but since you added styles like this `position: fixed!important;` to the image, this breaks everything. https://github.com/nk-o/jarallax/blob/master/src/jarallax.esm.js#L641-L649

I don't think I may help you with your custom code, this is not a Jarallax issue.
