### ISSUE TITLE
addEventListener() is an illegal function name

### ISSUE THREAD

**Issue by bradleyhodges** [nk-o/jarallax#78]
addEventListener() is an illegal function name, and when jarallax tries to reference it, it's attempting to attach an event listener, rather than execute the actual function. I suggest changing all references for 

**`addEventListener`**`(el, eventName, handler)`, to;
**`attachListener`**`(el, eventName, handler)`

**Comment by nk-o** [comment]
I don't think so. It will call the 'local' function `addEventListener` https://github.com/nk-o/jarallax/blob/master/dist/jarallax.js#L36. Only in the case, if this function does not exist it will call the global `addEventListener` (but this case will not happen, as this function always defined there).

Also, it will not conflict with the global function, just because code inside the iife https://github.com/nk-o/jarallax/blob/master/dist/jarallax.js#L7

In other side, we don't even need this function since we dropped support for older browsers. So, in the next update this function will be removed and used native addEventListener instead.
