### ISSUE TITLE
Some questions for Nikita and some fixes

### ISSUE THREAD

**Issue by afanjul** [nk-o/jarallax#9]
Hi Nikita, firstly let me say your plugin is awesome! I could review other ones and yours is the best in terms of optimization and features.

Reviewing your code, there is [a code block](https://github.com/nk-o/jarallax/blob/master/jarallax/jarallax.js#L246) when you do a while loop until reach document to know if there is a parent with transform style. In such a case you do a translateX(0) and translateY(0), why is this code block there? 

In another [code block](https://github.com/nk-o/jarallax/blob/master/jarallax/jarallax.js#L441), you do a "center parallax image" introducing a margin left, why you do that? We have some problems with that left margin.

**We cannot guess the reason for that code blocks. Could you clarify it?**

**Some fixes we did:**
There is an error with vimeo player, you can test it in your own demo website if you do: 
`jarallax(document.querySelectorAll('[data-jarallax], [data-jarallax-video]'), 'destroy');` and `jarallax(document.querySelectorAll('[data-jarallax], [data-jarallax-video]'));`.

So to avoid [vimeo errors with postMessage](https://github.com/vimeo/player-api/issues/55) method, we have introduced a "loaded" property to know when vimeo iframe is actually loaded and use that semaphore in play and pause code blocks:

so we do this in [this line](https://github.com/nk-o/jarallax/blob/master/jarallax/jarallax-video.js#L340):
```
 _this.$iframe.loaded = false;
hiddenDiv.appendChild(_this.$iframe);
document.body.appendChild(hiddenDiv);
_this.$iframe.addEventListener('load', function() {
       _this.$iframe.loaded = true;
});
```

and we do this in [these](https://github.com/nk-o/jarallax/blob/master/jarallax/jarallax-video.js#L161) two [lines](https://github.com/nk-o/jarallax/blob/master/jarallax/jarallax-video.js#L175):
```
if (this.$iframe.loaded){
    this.player.api('play');
}
```

thanks and regards,
Alex

PS. Sorry for not doing a pull request standard method...

**Comment by nk-o** [comment]
Hi, Alex.

Thank you for kind words.

* As you can see, I added comment for this code block
   `// check if one of parents have transform style (without this check, scroll transform will be inverted)`
   
   So, parallax will be inverted. This occurs because of parallax block have position fixed and this position breaks when one of the parents have transformations. You can test it by yourself by adding transform style on one of the parent after Jarallax init. [Stack Overflow](http://stackoverflow.com/a/15256339)

   For example this fix needs when you use parallax effect inside carousels (on one of my premium themes there is parallaxed carousel).

* Left margin for horizontal centering image inside block. Do you have troubles with it? Where I can check it? On demo page it working fine.
Example:
```
------------------------------
|           Image            |
|      |--------------|      |
| <--> |    Block     | <--> |
|      |--------------|      |
|                            |
------------------------------
````

* Thank you for fixes. I'll check it and update Jarallax soon.

Best regards, nK.

**Comment by afanjul** [comment]
Many thanks Nikita, we are adapting and fixing your code to our needs, when we finish adapting, I will send you the code so you could see if there is something interesting for you... ok?

**Could we ask another question?**: why do you remove user original background-image styles? It is for performance? any browser bug? just for security?
```
// remove default user background
    _this.css(_this.$item, {
      'background-image'      : 'none',
      'background-attachment' : 'scroll',
    'background-size'       : 'auto'
});
```
For our "Html Editor" needs, we need to keep the original background-image just there (ie. not remove original styles and recover later). Is there any problem with that? could we get into problems for some case?

thanks in advance

**Comment by nk-o** [comment]
Ok, will be appreciated for any code.

Background image removed for performance reasons. There is no need to show background image + parallax image because of parallax image shows over background image.
I think modern browsers don't have problems with performance, but I leave this code just for case if not.

If you want to return image back - just destroy jarallax.
